default_install_hook_types: [pre-commit, pre-push]
repos:
  - repo: local
    hooks:
      - id: spotlessFormatting
        name: spotlessFormatting
        entry: python3 scripts/run_gradle.py spotlessCheck
        pass_filenames: false
        language: system
        stages: [pre-commit, pre-push]

  - repo: local
    hooks:
      - id: pmdLinting
        name: pmdLinting
        entry: python3 scripts/run_gradle.py --info --stacktrace pmdMain
        pass_filenames: false
        language: system
        stages: [pre-commit, pre-push]

  - repo: local
    hooks:
      - id: pmdTest
        name: pmdTest
        entry: python3 scripts/run_gradle.py pmdTest
        pass_filenames: false
        language: system
        stages: [pre-commit, pre-push]

  - repo: local
    hooks:
      - id: test
        name: test
        entry: python3 scripts/run_gradle.py test
        pass_filenames: false
        language: system
        stages: [pre-push]
