services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /opt/
